In [3]:
# Load and activate the SQL extension to allows us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql is installed correctly. 

%load_ext sql

In [5]:
# Establish a connection to the local database using the '%sql' magic command,
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:ofge@localhost:3306/united_nations

In [16]:
%%sql

SELECT
    *
FROM
    Access_to_Basic_Services
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00'), Decimal('4.93')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00'), Decimal('4.96')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00'), Decimal('4.90')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00'), Decimal('4.85')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00'), Decimal('4.80'))]

## Task 1
Select data from the Sub-Saharan African region during the year 2020.

In [70]:
%%sql

SELECT
	Country_name,
	Time_period,
	Pct_managed_drinking_water_services,
	Pct_managed_sanitation_services,
	Est_population_in_millions,
	Est_gdp_in_billions
FROM
	united_nations.Access_to_Basic_Services
WHERE
	region = 'Sub-Saharan Africa'
AND
    Time_period = 2020;

 * mysql+pymysql://root:***@localhost:3306/united_nations
47 rows affected.

[('Burundi', 2020, Decimal('70.33'), Decimal('44.33'), Decimal('12.220227'), Decimal('2.65')),
 ('Djibouti', 2020, Decimal('69.00'), Decimal('56.00'), Decimal('1.090156'), Decimal('3.18')),
 ('Ethiopia', 2020, Decimal('58.00'), Decimal('11.67'), Decimal('117.190911'), Decimal('107.66')),
 ('Kenya', 2020, Decimal('67.00'), Decimal('33.67'), Decimal('51.985780'), Decimal('100.67')),
 ('Madagascar', 2020, Decimal('56.33'), Decimal('13.00'), Decimal('28.225177'), Decimal('13.05')),
 ('Malawi', 2020, Decimal('74.33'), Decimal('28.67'), Decimal('19.377061'), Decimal('12.18')),
 ('Mauritius', 2020, Decimal('100.00'), Decimal('96.00'), Decimal('1.265740'), Decimal('11.40')),
 ('Mayotte', 2020, Decimal('96.00'), Decimal('100.00'), None, None),
 ('Mozambique', 2020, Decimal('66.67'), Decimal('40.33'), Decimal('31.178239'), Decimal('14.03')),
 ('Rwanda', 2020, Decimal('66.33'), Decimal('64.00'), Decimal('13.146362'), Decimal('10.18')),
 ('RÃ©union', 2020, Decimal('100.00'), Decimal('100.00'), None, None),
 ('Somalia', 2020, Decimal('57.33'), Decimal('40.00'), Decimal('16.537016'), Decimal('6.88')),
 ('South Sudan', 2020, Decimal('48.33'), Decimal('22.33'), Decimal('10.606227'), None),
 ('Uganda', 2020, Decimal('61.00'), Decimal('21.67'), Decimal('44.404611'), Decimal('37.60')),
 ('United Republic of Tanzania', 2020, Decimal('65.00'), Decimal('34.00'), None, None),
 ('Zambia', 2020, Decimal('66.67'), Decimal('32.67'), Decimal('18.927715'), Decimal('18.11')),
 ('Zimbabwe', 2020, Decimal('68.00'), Decimal('36.33'), Decimal('15.669666'), Decimal('21.51')),
 ('Angola', 2020, Decimal('52.33'), Decimal('47.00'), Decimal('33.428486'), Decimal('53.62')),
 ('Cameroon', 2020, Decimal('64.00'), Decimal('43.00'), Decimal('26.491087'), Decimal('40.77')),
 ('Central African Republic', 2020, Decimal('38.33'), Decimal('15.00'), Decimal('5.343020'), Decimal('2.33')),
 ('Chad', 2020, Decimal('52.67'), Decimal('18.67'), Decimal('16.644701'), Decimal('10.72')),
 ('Congo', 2020, Decimal('69.00'), Decimal('17.67'), None, None),
 ('Democratic Republic of the Congo', 2020, Decimal('47.67'), Decimal('15.33'), None, None),
 ('Gabon', 2020, Decimal('73.33'), Decimal('47.00'), Decimal('2.292573'), Decimal('15.31')),
 ('Sao Tome and Principe', 2020, Decimal('77.33'), Decimal('46.00'), Decimal('0.218641'), Decimal('0.47')),
 ('Botswana', 2020, Decimal('89.67'), Decimal('74.33'), Decimal('2.546402'), Decimal('14.93')),
 ('Eswatini', 2020, Decimal('76.67'), Decimal('61.33'), Decimal('1.180655'), Decimal('3.98')),
 ('Lesotho', 2020, Decimal('76.33'), Decimal('49.67'), Decimal('2.254100'), Decimal('2.23')),
 ('Namibia', 2020, Decimal('83.67'), Decimal('35.00'), Decimal('2.489098'), Decimal('10.58')),
 ('South Africa', 2020, Decimal('92.00'), Decimal('78.67'), Decimal('58.801927'), Decimal('337.62')),
 ('Benin', 2020, Decimal('65.33'), Decimal('17.33'), Decimal('12.643123'), Decimal('15.65')),
 ('Burkina Faso', 2020, Decimal('53.33'), Decimal('25.00'), Decimal('21.522626'), Decimal('17.93')),
 ('Cabo Verde', 2020, Decimal('87.33'), Decimal('78.00'), Decimal('0.582640'), Decimal('1.70')),
 ("CÃ´te d'Ivoire", 2020, Decimal('70.67'), Decimal('34.67'), None, None),
 ('Gambia', 2020, Decimal('79.33'), Decimal('44.33'), None, None),
 ('Ghana', 2020, Decimal('84.67'), Decimal('23.00'), Decimal('32.180401'), Decimal('70.04')),
 ('Guinea', 2020, Decimal('67.33'), Decimal('32.33'), Decimal('13.205153'), Decimal('14.18')),
 ('Guinea-Bissau', 2020, Decimal('60.00'), Decimal('19.33'), Decimal('2.015828'), Decimal('1.43')),
 ('Liberia', 2020, Decimal('75.00'), Decimal('17.67'), Decimal('5.087584'), Decimal('3.04')),
 ('Mali', 2020, Decimal('83.67'), Decimal('46.00'), Decimal('21.224040'), Decimal('17.47')),
 ('Mauritania', 2020, Decimal('70.33'), Decimal('48.00'), Decimal('4.498604'), Decimal('8.41')),
 ('Niger', 2020, Decimal('57.33'), Decimal('24.67'), Decimal('24.333639'), Decimal('13.74')),
 ('Nigeria', 2020, Decimal('77.33'), Decimal('42.67'), Decimal('208.327405'), Decimal('432.20')),
 ('Saint Helena', 2020, Decimal('99.00'), Decimal('100.00'), None, None),
 ('Senegal', 2020, Decimal('85.00'), Decimal('57.00'), Decimal('16.436120'), Decimal('24.49')),
 ('Sierra Leone', 2020, Decimal('65.00'), Decimal('17.33'), Decimal('8.233970'), Decimal('4.06')),
 ('Togo', 2020, Decimal('70.67'), Decimal('20.00'), Decimal('8.442580'), Decimal('7.57'))]

## Task 2
Sometimes there are null values in our entries. Any country having Null values for their GDP should not be included in our query as they will not help us determine if there is any correlation between GDP and access to basic services. For this task determine if there are any NULL values in the GDP column

In [69]:
%%sql

SELECT
	Country_name,
	Time_period,
	Pct_managed_drinking_water_services,
	Pct_managed_sanitation_services,
	Est_gdp_in_billions,
    region
FROM
	united_nations.Access_to_Basic_Services
WHERE
	region = 'Sub-Saharan Africa'
AND
	Time_period = 2020
AND
	Est_gdp_in_billions IS NULL;

 * mysql+pymysql://root:***@localhost:3306/united_nations
9 rows affected.

[('Mayotte', 2020, Decimal('96.00'), Decimal('100.00'), None, 'Sub-Saharan Africa'),
 ('RÃ©union', 2020, Decimal('100.00'), Decimal('100.00'), None, 'Sub-Saharan Africa'),
 ('South Sudan', 2020, Decimal('48.33'), Decimal('22.33'), None, 'Sub-Saharan Africa'),
 ('United Republic of Tanzania', 2020, Decimal('65.00'), Decimal('34.00'), None, 'Sub-Saharan Africa'),
 ('Congo', 2020, Decimal('69.00'), Decimal('17.67'), None, 'Sub-Saharan Africa'),
 ('Democratic Republic of the Congo', 2020, Decimal('47.67'), Decimal('15.33'), None, 'Sub-Saharan Africa'),
 ("CÃ´te d'Ivoire", 2020, Decimal('70.67'), Decimal('34.67'), None, 'Sub-Saharan Africa'),
 ('Gambia', 2020, Decimal('79.33'), Decimal('44.33'), None, 'Sub-Saharan Africa'),
 ('Saint Helena', 2020, Decimal('99.00'), Decimal('100.00'), None, 'Sub-Saharan Africa')]

## Task 3
If there are any Null values exclude them from your query.

In [68]:
%%sql

SELECT
	Country_name,
	Time_period,
	Pct_managed_drinking_water_services,
	Pct_managed_sanitation_services,
	Est_gdp_in_billions,
    	region
FROM
	united_nations.Access_to_Basic_Services
WHERE
	region = 'Sub-Saharan Africa'
AND
	Time_period = 2020
AND
	Est_gdp_in_billions IS NOT NULL
ORDER BY Est_gdp_in_billions
LIMIT 10;

 * mysql+pymysql://root:***@localhost:3306/united_nations
10 rows affected.

[('Sao Tome and Principe', 2020, Decimal('77.33'), Decimal('46.00'), Decimal('0.47'), 'Sub-Saharan Africa'),
 ('Guinea-Bissau', 2020, Decimal('60.00'), Decimal('19.33'), Decimal('1.43'), 'Sub-Saharan Africa'),
 ('Cabo Verde', 2020, Decimal('87.33'), Decimal('78.00'), Decimal('1.70'), 'Sub-Saharan Africa'),
 ('Lesotho', 2020, Decimal('76.33'), Decimal('49.67'), Decimal('2.23'), 'Sub-Saharan Africa'),
 ('Central African Republic', 2020, Decimal('38.33'), Decimal('15.00'), Decimal('2.33'), 'Sub-Saharan Africa'),
 ('Burundi', 2020, Decimal('70.33'), Decimal('44.33'), Decimal('2.65'), 'Sub-Saharan Africa'),
 ('Liberia', 2020, Decimal('75.00'), Decimal('17.67'), Decimal('3.04'), 'Sub-Saharan Africa'),
 ('Djibouti', 2020, Decimal('69.00'), Decimal('56.00'), Decimal('3.18'), 'Sub-Saharan Africa'),
 ('Eswatini', 2020, Decimal('76.67'), Decimal('61.33'), Decimal('3.98'), 'Sub-Saharan Africa'),
 ('Sierra Leone', 2020, Decimal('65.00'), Decimal('17.33'), Decimal('4.06'), 'Sub-Saharan Africa')]

## Task 4
Lets get an idea if there's any correlation between the GDP and access to basic services for the top 5 economies in Sub-Saharan Africr. The top 5 GDP's are : ('Nigeria','South Africa','Ethiopia','Kenya','Ghana'). Make sure your query only includes these countries.

In [66]:
%%sql

SELECT
	Country_name,
	Time_period,
	Pct_managed_drinking_water_services,
	Pct_managed_sanitation_services,
	Est_population_in_millions,
	Est_gdp_in_billions
FROM
	united_nations.Access_to_Basic_Services

WHERE
	Region = 'Sub-Saharan Africa'
AND
Time_period = 2020

AND
	Est_gdp_in_billions IS NOT NULL

AND
	Country_name  NOT IN ('Nigeria','South Africa','Ethiopia','Kenya','Ghana')
ORDER BY Est_gdp_in_billions
limit 10;

 * mysql+pymysql://root:***@localhost:3306/united_nations
10 rows affected.

[('Sao Tome and Principe', 2020, Decimal('77.33'), Decimal('46.00'), Decimal('0.218641'), Decimal('0.47')),
 ('Guinea-Bissau', 2020, Decimal('60.00'), Decimal('19.33'), Decimal('2.015828'), Decimal('1.43')),
 ('Cabo Verde', 2020, Decimal('87.33'), Decimal('78.00'), Decimal('0.582640'), Decimal('1.70')),
 ('Lesotho', 2020, Decimal('76.33'), Decimal('49.67'), Decimal('2.254100'), Decimal('2.23')),
 ('Central African Republic', 2020, Decimal('38.33'), Decimal('15.00'), Decimal('5.343020'), Decimal('2.33')),
 ('Burundi', 2020, Decimal('70.33'), Decimal('44.33'), Decimal('12.220227'), Decimal('2.65')),
 ('Liberia', 2020, Decimal('75.00'), Decimal('17.67'), Decimal('5.087584'), Decimal('3.04')),
 ('Djibouti', 2020, Decimal('69.00'), Decimal('56.00'), Decimal('1.090156'), Decimal('3.18')),
 ('Eswatini', 2020, Decimal('76.67'), Decimal('61.33'), Decimal('1.180655'), Decimal('3.98')),
 ('Sierra Leone', 2020, Decimal('65.00'), Decimal('17.33'), Decimal('8.233970'), Decimal('4.06'))]

## Task 5
We only looked at 5 countries in the previous query. Lets have a look at the rest of Sub-Saharan Africa . Exclude the countries mentioned in the previous task

In [62]:
%%sql

SELECT
	Country_name,
	Time_period,
	Pct_managed_drinking_water_services,
	Pct_managed_sanitation_services,
	Est_population_in_millions,
	Est_gdp_in_billions
FROM
	united_nations.Access_to_Basic_Services

WHERE
	Region = 'Sub-Saharan Africa'
AND
Time_period = 2020

AND
	Est_gdp_in_billions IS NOT NULL

AND
	Country_name IN ('Nigeria','South Africa','Ethiopia','Kenya','Ghana')
ORDER BY Pct_managed_sanitation_services;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Ethiopia', 2020, Decimal('58.00'), Decimal('11.67'), Decimal('117.190911'), Decimal('107.66')),
 ('Ghana', 2020, Decimal('84.67'), Decimal('23.00'), Decimal('32.180401'), Decimal('70.04')),
 ('Kenya', 2020, Decimal('67.00'), Decimal('33.67'), Decimal('51.985780'), Decimal('100.67')),
 ('Nigeria', 2020, Decimal('77.33'), Decimal('42.67'), Decimal('208.327405'), Decimal('432.20')),
 ('South Africa', 2020, Decimal('92.00'), Decimal('78.67'), Decimal('58.801927'), Decimal('337.62'))]